adj0 = input("Please enter an adjective: ")
thing0 = input("Please enter an object: ")
thing1 = input("Please enter another object: ")
thing2 = input("Please enter ANOTHER object: ")
person = input("Please enter a person, thing, or animal: ")
town0 = input("Please enter the name of a town or city: ")
adj1 = input("Please enter an adjective: ")
inter0 = input("Please enter an interjection: ")
town1 = input("Please enter the name of a town or city: ")
adj2 = input("Please enter an adjective: ")
inter1 = input("Please enter an interjection: ")
town2 = input("Please enter the name of a town or city: ")
adj3 = input("Please enter an adjective: ")
inter2 = input("Please enter an interjection: ")
liquid = input("Please enter a liquid: ")
town3 = input("Please enter the name of a town or city: ")

story = ("Once upon a time, there were three " + adj0 + " pigs. The first pig built his house out of " + thing0 + ". The second pig built his house out of " + thing1 + ". The third pig built his house out of " + thing2 + ". One day a wolf went looking for his " + person + ". He thought the three little pigs took his " + person + ". \"Those pigs took my " + person + "!\" He went to the first pigs house in " + town0 + ". Welcome to " + town0 + "! The wolf knocked on the door and said " + adj1 + " pig " + adj1 + " pig. Let me in! Not by the hair of my chinny chin chin. The wolf got mad and said " + inter0 + "! And he huffed and puffed and blew the house down. The first pig ran to the second pigs house in " + town1 + ". Welcome to " + town1 + "! The wolf knocked on the door and said " + adj2 + " pig " + adj2 + " pig. Let me in! Not by the hair of my chinny chin chin. The wolf got mad and said " + inter1 + "! And he huffed and puffed and blew the house down. The first pig ran to the second pigs house in" + town2 + ". Welcome to " + town2 + "! The wolf knocked on the door and said " + adj3 + " pig " + adj3 + " pig. Let me in! Not by the hair of my chinny chin chin. The wolf got mad and said " + inter2 + "! And he huffed and puffed and huffed and puffed and huffed and pulled... but the house didn't fall down.  The wolf decides to go down the chimney.  The pigs hurried to the fireplace, made a fire and boiled some " + liquid + ". The wolf came down the chimney and fell into the boiling " + liquid + "! He burned his tail and ran all the way home to " + town3 + "!")
print(story)
